[font]
size = 14
normal = { family = "BlexMono Nerd Font", style = "regular" }

[window]
opacity=0.9

[general]
import = [
	#"/home/joona/dotfiles/alacritty/.config/alacritty/solarized-dark.toml"
	"/home/joona/dotfiles/alacritty/.config/alacritty/ayu-dark.toml"
]
