[[language]]
name = "typescript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "css"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "html"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = " " }

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = " " }
