icons_format = "{icon}"

[theme]
#theme = "solarized-dark"
theme = "native"

#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"

#[[block]]
#block = "net"
#device = "koululappari"
#format = "$icon  $device"
#inactive_format = "Disconnected"

[[block]]
block = "net"
format = "$icon  $device"
inactive_format = "Disconnected"

[[block]]
block = "sound"
#[[block.click]]
#button = "left"
#cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "battery"
format = "$icon  $percentage"
full_format = "$icon  $percentage FULL"
charging_format = "$icon $percentage CHR"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d.%m %R') "
